# Generated by Django 3.1.1 on 2020-09-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('phone', models.TextField(blank=True, max_length=700)),
                ('email', models.TextField(blank=True, max_length=700)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
